### ISSUE TITLE
Adding Scanner and Valuer interface for LSN type

### ISSUE THREAD

**Issue by diabloneo** [jackc/pglogrepl#15]
Hi, @jackc 

I think it will make users a lot more convenient if adding implementation of `database/sql.Scanner` and `database/sql/driver/driver.Valuer` to type `LSN`. But I'm not sure about which place to put the implemantation, this lib, or `github.com/jackc/pgtype` ? Any suggestion?

**Comment by jackc** [comment]
Ordinarily, this would be part of `pgtype` but since this is so specific to replication I think it would be appropriate to this package.

**Comment by diabloneo** [comment]
Resolved by #16
