### ISSUE TITLE
receive message failed: read tcp: i/o timeout

### ISSUE THREAD

**Issue by joeyzhouy** [jackc/pglogrepl#2]
follow example 
```
messageTimeout := time.Second * 2
nextMessageTimeDeadline := time.Now().Add(messageTimeout)
ctx, cancel := context.WithDeadline(context.Background(), nextMessageTimeDeadline)
msg, err := conn.ReceiveMessage(ctx)
cancel()
if err != nil {
    if errors.Is(err, context.DeadlineExceeded) {
	continue
    }
    log.Log.Fatal("ReceiveMessage failed", zap.Error(err))
}
```
get error message:
```
"receive message failed: read tcp 127.0.0.1:62502->127.0.0.1:5432: i/o timeout"
```

I think `timeout` error like `context.DeadlineExceeded`, program can ignore.
But i can not judge error type，because of return `pgconnError`

**Comment by jackc** [comment]
The demo code was written against a pre-release version of pgconn. I've updated the go.mod dependency and the demo code.

Timeouts should now be tested with `pgconn.Timeout`.

```go
		ctx, cancel := context.WithDeadline(context.Background(), nextStandbyMessageDeadline)
		msg, err := conn.ReceiveMessage(ctx)
		cancel()
		if err != nil {
			if pgconn.Timeout(err) {
				continue
			}
			log.Fatalln("ReceiveMessage failed:", err)
		}
```

Should be fixed now.

**Comment by joeyzhouy** [comment]
@jackc thanks

**Comment by joeyzhouy** [comment]
By the way, `pglogrepl` will consider implementing data parsing(For example，`test_decoding` output plugin)?

**Comment by jackc** [comment]
It's possible, but it's not something I will be able to personally work on in the immediate future.
