### ISSUE TITLE
Received unexpected message

### ISSUE THREAD

**Issue by zhanghaiyang9999** [jackc/pglogrepl#24]
postgresql version: 10(OS:ubuntu18)
when insert record, received the error message like the following:
2021/11/25 21:56:21 Received unexpected message: &pgproto3.ErrorResponse{Severity:"ERROR", SeverityUnlocalized:"ERROR", Code:"42704", Message:"publication \"pglogrepl_demo\" does not exist", Detail:"", Hint:"", Position:0, InternalPosition:0, InternalQuery:"", Where:"slot \"pglogrepl_demo\", output plugin \"pgoutput\", in the change callback, associated LSN 0/16AD8B0", SchemaName:"", TableName:"", ColumnName:"", DataTypeName:"", ConstraintName:"", File:"pg_publication.c", Line:402, Routine:"GetPublicationByName", UnknownFields:map[uint8]string(nil)}
2021/11/25 21:56:21 Received unexpected message: &pgproto3.ReadyForQuery{TxStatus:0x49}

**Comment by Jille** [comment]
https://github.com/jackc/pglogrepl/pull/32 handles the first message by returning an error.
