### ISSUE TITLE
For update message, the OldTuple is nil

### ISSUE THREAD

**Issue by zhanghaiyang9999** [jackc/pglogrepl#38]
I used the example code to test the logic replication, Insert and Delete operations are good, but the Update operation is incorrect, the OldTuple is nil for the Update event. @jackc 
BTW: the test table has primary key.
![image](https://user-images.githubusercontent.com/11850091/192928758-f944523e-2dc6-495f-ab94-bf350787bf76.png)

**Comment by JordanP** [comment]
Could you try setting `ALTER TABLE mytable REPLICA IDENTITY FULL;` ? You should understand the impact before doing that in prod though.

**Comment by zhanghaiyang9999** [comment]
@JordanP Thanks, if I executed the sql "ALTER TABLE mytable REPLICA IDENTITY FULL", the OldTuple is not nil, But my test table has primary key, I think the identify FULL just for the table that has not the primary key case.

**Comment by JordanP** [comment]
@zhanghaiyang9999 not exactly.  This [page](https://paquier.xyz/postgresql-2/postgres-9-4-feature-highlight-replica-identity-logical-replication/) says 
```
In the case of DEFAULT, old tuple data is only identified with the primary key of the table. This data is written into WAL only when at least one column of the primary key is updated. Columns that are not part of the primary key do not have their old value written.
``` 

Whereas with `FULL`:
```
In the case of FULL, all the column values are written to WAL all the time. This is the most verbose, and as well the most resource-consuming mode. Be careful here particularly for heavily-updated tables.
```

**Comment by zhanghaiyang9999** [comment]
Thanks @JordanP for the detail.
I have another issue, the pglogrepl can't capture one of my test tables changes such as insert, update and delete.
but all the other test tables worked well, except this one table. I can't confirm this is the pglogrepl issue or the postgresql issue.
