### ISSUE TITLE
Can pglogrepl support standard *sql.DB?

### ISSUE THREAD

**Issue by zhanghaiyang9999** [jackc/pglogrepl#39]
Now pglogrepl just can only use *PgConn, but *PgConn and *sql.DB have many difference, for example, the interfaces are different, and for example, the sql.DB has auto reconnect mechanism if the network is broken, but PgConn doesn't,
If the network is broken, the pglogrepl can't resume the replication.

@jackc Can pglogrepl support standard *sql.DB in future version? Thanks!

**Comment by jackc** [comment]
Very unlikely. pglogrepl relies on lower level and PostgreSQL specific interfaces that `*sql.DB` doesn't offer.
