### ISSUE TITLE
interest in supporting physical replication?

### ISSUE THREAD

**Issue by tcrayford** [jackc/pglogrepl#4]
Hi!

As noted in https://github.com/jackc/pgconn/issues/23, I'm interested in doing custom physical replication clients (mostly for learning for my own interest). I believe the only change needed for this repo would be to allow `START_REPLICATION` to take `PHYSICAL` instead of `LOGICAL`.

Would you be accepting of a PR that makes that possible, maybe by a flag in `StartReplicationOptions` ?

I also wonder if that should cause this repo to change name - as it now supports physical as well as logical rep. I'm personally not that fussed though.

**Comment by jackc** [comment]
I think a flag in `StartReplicationOptions` would be fine.
