### ISSUE TITLE
Can *PgConn support reconnect automatically?

### ISSUE THREAD

**Issue by zhanghaiyang9999** [jackc/pglogrepl#42]
Hi @jackc ,
Can *PgConn Support reconnect automatically? if the network is blocken, the replication can't continue even if the network is connected in a few seconds.

**Comment by jackc** [comment]
I don't think `*pgconn.PgConn` is the best place to handle automatic reconnection. It doesn't know the state of whatever is using it at a higher level and it could not automatically restore that state if it did. I think this feature would need to be at a higher level.
