### ISSUE TITLE
Upgrade dependency pgx to v5.5.4?

### ISSUE THREAD

**Issue by bqluan** [jackc/pglogrepl#62]
pgx v5.5.4 changes signature for func `CopyData.Encode` in [this commit](https://github.com/jackc/pgx/commit/adbb38f298c76e283ffc7c7a3f571036fea47fd4#) by returning an `error`. This project uses the function with previous signature (without `error`). Is it ok to upgrade to pgx v5.5.4?

**Comment by jackc** [comment]
Yes. Done in 828fbfe908e97cfeb409a17e4ec339dede1f1a17.
